# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ if not .Values.components.openVsxProxy.disabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvsx-proxy
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: openvsx-proxy
    kind: service-account
    stage: {{ .Values.installation.stage }}
{{- end -}}
