# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.openVsxProxy -}}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}
{{- if not $comp.disabled -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: openvsx-proxy
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: openvsx-proxy
    kind: deployment
    stage: {{ .Values.installation.stage }}
spec:
  selector:
    matchLabels:
      app: {{ template "gitpod.fullname" . }}
      component: openvsx-proxy
      kind: pod
      stage: {{ .Values.installation.stage }}
  replicas: {{ $comp.replicas | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: openvsx-proxy
      labels:
        app: {{ template "gitpod.fullname" . }}
        component: openvsx-proxy
        kind: pod
        stage: {{ .Values.installation.stage }}
    spec:
{{ include "gitpod.pod.affinity" $this | indent 6 }}
      serviceAccount: openvsx-proxy
      containers:
      - name: openvsx-proxy
        image: {{ template "gitpod.comp.imageFull" $this }}
        args:
        - /config/config.json
{{ include "gitpod.container.imagePullPolicy" $this | indent 8 }}
{{ include "gitpod.container.resources" $this | indent 8 }}
{{ include "gitpod.container.ports" $this | indent 8 }}
        securityContext:
          privileged: false
        volumeMounts:
        - name: config
          mountPath: "/config"
{{ include "gitpod.container.defaultEnv" (dict "root" . "gp" $.Values "comp" $comp) | indent 8 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "gitpod.comp.configMap" $this }}
{{ toYaml .Values.defaults | indent 6 }}
{{ end }}
